# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by Debian postinst script
# Date: Tue, 04 Sep 2012 19:48:03 -0700

*               @ALL          1
*               @user         8
wiki:*	@user	1
braincase:*	@user	0
